/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package juego;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author estadm
 */
public class Principal extends javax.swing.JFrame implements KeyListener{

    private int pas=0;
    //public static javax.swing.JLabel jLabel2;
    public Principal() 
    {
        add(new PanelImagen());
        setSize(1300,700);
        setTitle("CRAZY DEFENDER");
        setResizable(true);
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        addKeyListener(this);
        PanelImagen.valores(0,0,"PAG2.jpg");
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setBackground(new java.awt.Color(255, 0, 153));
        jLabel2.setText("hola");
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        Principal p = new Principal();
    }

    /**
     *
     * @param ke
     */
    @Override
    public void keyPressed(KeyEvent ke) 
    {
        PanelImagen p = new PanelImagen();
        //pas=true;
        JFrame f = new JFrame();
        if (pas==0)
        {
            if (ke.getKeyCode() == 38)
            {
                PanelImagen.valores(0,0,"PAG.jpg");
                setSize(1300,701);
                setSize(1300,700); 
                pas=2;  
            }
            else if (ke.getKeyCode() == 40)
            {
                PanelImagen.valores(0,0,"PAG1.jpg");
                setSize(1300,701);
                setSize(1300,700); 
                pas=1;  
            }
            
        }
        else if (pas==1)
        {
            if (ke.getKeyCode() == 38)
            {
                PanelImagen.valores(0,0,"PAG2.jpg");
                setSize(1300,701);
                setSize(1300,700); 
                pas=0;  
            }
            else if (ke.getKeyCode() == 40)
            {
                PanelImagen.valores(0,0,"PAG.jpg");
                setSize(1300,701);
                setSize(1300,700); 
                pas=2;  
            }
            
        }
        else
        {
            if (ke.getKeyCode() == 38)
            {
                PanelImagen.valores(0,0,"PAG1.jpg");
                setSize(1300,701);
                setSize(1300,700); 
                pas=1;  
            }
            else if (ke.getKeyCode() == 40)
            {
                PanelImagen.valores(0,0,"PAG2.jpg");
                setSize(1300,701);
                setSize(1300,700); 
                pas=0;  
            }
         
        }
       
    
    }
    @Override
    public void keyTyped(KeyEvent ke) 
    {
    }
    @Override
    public void keyReleased(KeyEvent ke) 
    {
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

